- hosts: k8s-cluster01
  vars:
    ImageNameDev: ""
    ImageNameProd: ""
    Namespace: ""
    imageTag: ""
  tasks:
  - name: Delete Deployed Before
    command: "helm delete --purge jaguar-apps-development"
    ignore_errors: yes
  - name: Deploy Apps Jaguar Apps Dev
    command: "helm install --name=jaguar-apps-{{ Namespace }}  --namespace={{ Namespace }} ./helm/jaguar-apps --set image.repository={{ ImageNameDev }} --set image.tag={{ imageTag }} --set namespace={{ Namespace }}"
    ignore_errors: yes
